export const anggota = [
    { nama: "MTsN 3 Medan",                    type: "Pendiri",                                   angkatan: ["1"],      email: "username@mail.com",                status: "Aktif",  nsm: "10264578",   khusus: true, tipe: "a",foto:"img/download.png", tipe: "a" }, // data khusus
    { nama: "Ahmad Fauzi",                     type: "Pembina",                                   angkatan: ["2"],      email: "Di rahasiakan",                    status: "Aktif",                     khusus: true, tipe: "b",foto:"img/pas photo/pak fauzi.jpeg"}, // data khusus
    { nama: "Fathoni Hidayah Sakti, S.kom.",   type: "Pelatih",                                   angkatan: ["2"],      email: "Di rahasiakan",                    status: "Aktif",                     khusus: true, tipe: "b",foto:"img/pas photo/pak toni copy.jpeg"}, // data khusus
    { nama: "Muhammad Fachri",                 type: "Ketua Angkatan 1 | Angkatan 1", kelas: "-", angkatan: ["4", "3"], email: "muhammadfachri353@gmail.com",      status: "Alumni",nisn: "0101203482", khusus: true,           foto:"img/pas photo/fahri.jpg",},
    { nama: "Muhammad Arkan Muiz",             type: "Ketua Angkatan 2 | Angkatan 1", kelas: "9", angkatan: ["4", "3"], email: "arkanmuhammad239@gmail.com",       status: "Aktif", nisn: "0102291858", khusus: true,           foto:"img/pas photo/foto.jpg",},
    { nama: "Rifqi Haziq Muzhaffar",           type: "Angkatan 1",                    kelas: "9", angkatan: ["4"],      email: "rifqiyapping@gmail.com",           status: "Aktif" ,nisn: "0114650658",                         foto:"img/pas photo/foto rifqi.jpeg",},
    { nama: "Bintang Aulia",                   type: "Angkatan 1",                    kelas: "-", angkatan: ["4"],      email: "-",                                status: "Alumni",nisn: "-",                                  foto:"", },
    { nama: "Qottrun Nada",                    type: "Angkatan 1",                    kelas: "-", angkatan: ["4"],      email: "-",                                status: "Alumni",nisn: "-",                                  foto:"", },
    { nama: "Nadhira Azkiya Nasution ",        type: "Angkatan 1",                    kelas: "-", angkatan: ["4"],      email: "nadhiraazkiya686@gmail.com",       status: "Alumni",nisn: "0102291858",                         foto:"img/pas photo/pas nadhira", },
    { nama: "Muhammad Zidane Alfahri",         type: "Angkatan 1",                    kelas: "-", angkatan: ["4"],      email: "-",                                status: "Alumni",nisn: "-",                                  foto:"" },
    { nama: "Divyanisa Almyra Prameswari",     type: "Angkatan 1",                    kelas: "-", angkatan: ["4"],      email: "divyanisarevanzaadelyo@gmail.com", status: "Alumni",nisn: "0115180887",                         foto:"img/pas photo/kak divy.jpg", },
    { nama: "Dastan Afroza",                   type: "Angkatan 1",                    kelas: "9", angkatan: ["4"],      email: "dastanafroza@gmail.com",           status: "OUT",   nisn: "3117454231",                         foto:"img/pas photo/dastan.jpg",},
    { nama: "Faqih Ahmad Zuhdi",               type: "Angkatan 1",                    kelas: "9", angkatan: ["4"],      email: "-",                                status: "OUT",   nisn: "-",                                  foto:"",},
    { nama: "Mooftya",                         type: "Angkatan 1",                    kelas: "9", angkatan: ["4"],      email: "dastanafroza@gmail.com",           status: "OUT",   nisn: "3117454231",                         foto:"img/pas photo/dastan.jpg",},
    { nama: "Muhammad Afiq Sembiring",         type: "Angkatan 1",                    kelas: "-", angkatan: ["4"],      email: "-",                                status: "Alumni",nisn: "-",                                  foto:"",},
    { nama: "Adwa Mughis Mahirdi",             type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "adwatugassekolah@gmail.com",       status: "OUT", nisn: "0124662961",                         foto:"img/pas photo/adwa.jpeg"},
    { nama: "Nauval Aulia Simanjuntak",        type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "nauvalauliasimanjuntak@gmail.com", status: "Aktif", nisn: "0122931880",                         foto:"img/pas photo/noval.jpg"},
    { nama: "Danish Sulthan Alfian",           type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "danizznizzda35@gmail.com",         status: "Aktif", nisn: "3129451466",                         foto:"img/pas photo/danish.jpg"},
    { nama: "Atharahardian Revanza Adelyo",    type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "revanzadelyo55@gmail.com",         status: "Aktif", nisn: "0128753159",                         foto:"img/pas photo/revan.jpg"},
    { nama: "M.SHIDDIQ AR-RIDHO ",             type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "mshiddiq192@gmail.com",            status: "Aktif", nisn: "0112423032",                         foto:"img/pas photo/shiddiq.jpg"},
    { nama: "Arfa maula shafi",                type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "arfamaulashafi13@gmail.com",       status: "Aktif", nisn: "3135432525",                         foto:"img/pas photo/arfa.jpg"},
    { nama: "Fathir Ramadhan Zulfy ",          type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "fathirramadhanzulfy@gmail.com",    status: "Aktif", nisn: "0123197853",                         foto:"img/pas photo/fathir.jpg"},
    { nama: "Muhammad Zidad Asyami Ruzain",    type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "syamisyami15@gmail.com",           status: "Aktif", nisn: "3112208239",                         foto:"img/pas photo/ziyad.jpg"},
    { nama: "Ibnu Pramudya",                   type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "-",                                status: "Aktif", nisn: "-",                                  foto:"", },
    { nama: "Yasin",                           type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "-",                                status: "Aktif", nisn: "-",                                  foto:"", },
    { nama: "Divian",                          type: "Angkatan 2",                    kelas: "8", angkatan: ["5"],      email: "-",                                status: "Aktif", nisn: "-",                                  foto:"", },
    { nama: "Teuku Fahri",                     type: "Angkatan 3",                    kelas: "7", angkatan: ["6"],      email: "teukualfarabi493@gmail.com",       status: "Aktif", nisn: "5954260913" ,                        foto:""},
    { nama: "Zaki Rizal",                      type: "Angkatan 3",                    kelas: "7", angkatan: ["6"],      email: "zakirizal268@gmail.com",           status: "Aktif", nisn: "01324567004",                        foto:"img/pas photo/zaki.jpg"},
    { nama: "Muhammad alif alfayed sembiring", type: "Angkatan 3",                    kelas: "7", angkatan: ["6"],      email: "fazelsembiring12@gmail",           status: "Aktif", nisn: "3129552372" ,                        foto:"img/pas photo/alfayed.jpg"},
    { nama: "Alfarizqi sudiro",                type: "Angkatan 3",                    kelas: "7", angkatan: ["6"],      email: "Alfarizqisudiro619@gmail.com",     status: "Aktif", nisn: "3133865942" ,                        foto:"img/pas photo/alfarizqi.jpg"},
    { nama: "Fadyan ilmi Nasution ",           type: "Angkatan 3",                    kelas: "7", angkatan: ["6"],      email: "fadyanilmi@gmail.com",             status: "Aktif", nisn: "0133556388" ,                        foto:"img/pas photo/fadyan.jpg"},
    { nama: "Muhammad izza husainy ",          type: "Angkatan 3",                    kelas: "7", angkatan: ["6"],      email: "izzahusainy888@gmail.com",         status: "Aktif", nisn: "3134857809" ,                        foto:"img/pas photo/izza.png"},
    { nama: "Mufadhil afif rasya",             type: "Angkatan 3",                    kelas: "7", angkatan: ["6"],      email: "mufadhilrasya@gmail.com",          status: "Aktif", nisn: "3134857809" ,                        foto:"img/pas photo/afif.jpeg"},
    { nama: "Zahra Safira Purnama ",           type: "Angkatan 3",                    kelas: "7", angkatan: ["6"],      email: "zahrasafirapurnama12@gmail.com",   status: "Aktif", nisn: "0127904374" ,                        foto:"img/pas photo/zahra.jpg"},
    { nama: "Nasywa Athaya Fawwaz",            type: "Angkatan 3",                    kelas: "7", angkatan: ["6"],      email: "nasywafawwaz39@gmail.com",         status: "Aktif", nisn: "0128764622" ,                        foto:"img/pas photo/nasywa.jpg"},

  ];

